// This file is part of meshoptimizer library and is distributed under the terms of MIT License.
// Copyright (C) 2016-2021, by Arseny Kapoulkine (arseny.kapoulkine@gmail.com)
var MeshoptEncoder = (function() {
	"use strict";

	// Built with clang version 13.0.0 (https://github.com/llvm/llvm-project fd1d8c2f04dde23bee0fb3a7d069a9b1046da979)
	// Built from meshoptimizer 0.17
	var wasm = "B9h79tEBBBENQ9gEUEU9gEUB9gBB9gVUUUUUEU9gDUUEU9gLUUUUEU9gIUUUEU9gVUUUUUB9gLUUUUB9gD99UE99Ie8aDILEVOLEVLRRRRRWWVBOOBEdddLVE9wEIIVIEBEOWEUEC+Q/KEKR/QIhO9tw9t9vv95DBh9f9f939h79t9f9j9h229f9jT9vv7BB8a9tw79o9v9wT9fw9u9j9v9kw9WwvTw949C919m9mwvBE8f9tw79o9v9wT9fw9u9j9v9kw9WwvTw949C919m9mwv9C9v919u9kBDe9tw79o9v9wT9fw9u9j9v9kw9WwvTw949Wwv79p9v9uBIy9tw79o9v9wT9fw9u9j9v9kw69u9kw949C919m9mwvBL8e9tw79o9v9wT9fw9u9j9v9kw69u9kw949C919m9mwv9C9v919u9kBO8a9tw79o9v9wT9fw9u9j9v9kw69u9kw949Wwv79p9v9uBRe9tw79o9v9wT9fw9u9j9v9kw69u9kw949Twg91w9u9jwBWA9tw79o9v9wT9fw9u9j9v9kw69u9kw949Twg91w9u9jw9C9v919u9kBdl9tw79o9v9wT9fw9u9j9v9kws9p2Twv9P9jTBQk9tw79o9v9wT9fw9u9j9v9kws9p2Twv9R919hTBKl9tw79o9v9wT9fw9u9j9v9kws9p2Twvt949wBXe9tw79o9v9wT9f9v9wT9p9t9p96w9WwvTw94j9h9j9owBSA9tw79o9v9wT9f9v9wT9p9t9p96w9WwvTw94j9h9j9ow9TTv9p9wBZA9tw79o9v9wT9f9v9wT9p9t9p96w9WwvTw94swT9j9o9Sw9t9h9wBhL79iv9rBodWEBCEKDqxQ/b9j8aDBK+hcEYU8jJJJJBCJO9rGV8kJJJJBCBHODNALCEFAE0MBABCBrBJ+KJJBC+gEv86BBAVCJDFCBCJDZnJJJB8aDNAItMBAVCJDFADALZ+TJJJB8aKABAEFHRABCEFHEAVALFCBCBCJDAL9rALCfE0eZnJJJB8aAVAVCJDFALZ+TJJJBHWCJ/ABAL9uC/wfBgGOCJDAOCJD6eHdDNDNALtMBCBHQINAQAI9PMDAWCJLFCBCJDZnJJJB8aAdAIAQ9rAQAdFGOAI6eGKCSFGXCL4CIFCD4HMADAQAL2FHpDNDNDNDNDNDNAXC9wgGStMBAIAOAIAO6eHZAKC9+gHhCEHoAKCEgHaADALAQCEFGc2FHxCBHqAEHlXEKAKtMEAIAOAIAO6eHkAKC9+gHyCEHoAKCEgH8aADALAQCEFGe2FH3CBH5INAWA5FrBBH8eDNDNAkAe9HMBCBHXA5HOXEKCBHXA5HOAyH8fINAWCJLFAXFGAApAOFrBBGlA8e9rG8eCETA8eCkTCk91CR4786BBAACEFA3AOFrBBG8eAl9rGACETAACkTCk91CR4786BBAXCDFHXAOALFALFHOA8fC9+FG8fMBKKDNA8atMBAWCJLFAXFApAOFrBBA8e9rGOCETAOCkTCk91CR4786BBKARAE9rAM6MIAECBAMZnJJJBGEtMIAEAMFHEA5CEFG5AL6HoA5AL9HMBXLKKINDNAKtMBAWAqFrBBHXCBHODNDNAZAc9HMBAqHEXEKCBHOAqHEAhH8eINAWCJLFAOFG8fApAEFrBBGAAX9rGXCETAXCkTCk91CR4786BBA8fCEFAxAEFrBBGXAA9rG8fCETA8fCkTCk91CR4786BBAOCDFHOAEALFALFHEA8eC9+FG8eMBKKAatMBAWCJLFAOFApAEFrBBAX9rGECETAECkTCk91CR4786BBKARAl9rAM6MDCBHHAlCBAMZnJJJBGGAMFHEAWCJLFH8jINARAE9rCk6MIAWCJLFAHFGyrBDHXCUHODNAyrBBGAAyrBEG8evCfEgMBCBH8eAXCfEgMBCBHXDNAyrBIMBAyrBLMBAyrBVMBAyrBOMBAyrBRMBAyrBWMBAyrBdMBAyrBQMBAyrBKMBAyrBXMBAyrBMMBCBH8eAyrBpMECBHXCUCBAyrBSeHOKCBH8eKDNDNDNDNCLCDCECWAOCZ6G8feCVCLAACfEgGACD0eA8eCfEgG8eCD0FAXCfEgGXCD0FAyrBIGlCD0FAyrBLG3CD0FAyrBVG5CD0FAyrBOGkCD0FAyrBRG8aCD0FAyrBWGeCD0FAyrBdG8kCD0FAyrBQG8lCD0FAyrBKG8mCD0FAyrBXG8nCD0FAyrBMGYCD0FAyrBpG8pCD0FAyrBSGiCD0FG8rAOCZA8feG8s6GOeCdCWAACp0eA8eCp0FAXCp0FAlCp0FA3Cp0FA5Cp0FAkCp0FA8aCp0FAeCp0FA8kCp0FA8lCp0FA8mCp0FA8nCp0FAYCp0FA8pCp0FAiCp0FA8rA8sAOe6GXeG8eCUFpDIEBKAGAHCO4FGAAArBBCDCIAXeAHCI4COgTv86BBA8eCW9HMEAEAy8pBB83BBAECWFAyCWF8pBB83BBAECZFHEXDKAGAHCO4FGAAArBBCEAHCI4COgTv86BBKCDCLCWCEA8feAOeAXeGkCpgH5AkCEgH8kCUA8eTCU7HOCBHeA8jH3INAEH8aCBHECBHXDNAkCEsMBCBHECBHXINA3AEFG8fCEFrBBGAAOAAAOCfEgGl6eA8frBBG8fAOA8fAl6eAXCfEgA8eTvCfEgA8eTvHXA5AECDFGE9HMBKKDNA8ktMBAyAEAeFFrBBGEAOAEAOCfEg6eAXCfEgA8eTvHXKA8aAX86BBA3AkFH3A8aCEFHEAeAkFGeCZ6MBKDNAyrBBGXAOCfEgGO6MBA8aAX86BEA8aCDFHEKDNAyrBEGXAO6MBAEAX86BBAECEFHEKDNAyrBDGXAO6MBAEAX86BBAECEFHEKDNAyrBIGXAO6MBAEAX86BBAECEFHEKDNAyrBLGXAO6MBAEAX86BBAECEFHEKDNAyrBVGXAO6MBAEAX86BBAECEFHEKDNAyrBOGXAO6MBAEAX86BBAECEFHEKDNAyrBRGXAO6MBAEAX86BBAECEFHEKDNAyrBWGXAO6MBAEAX86BBAECEFHEKDNAyrBdGXAO6MBAEAX86BBAECEFHEKDNAyrBQGXAO6MBAEAX86BBAECEFHEKDNAyrBKGXAO6MBAEAX86BBAECEFHEKDNAyrBXGXAO6MBAEAX86BBAECEFHEKDNAyrBMGXAO6MBAEAX86BBAECEFHEKDNAyrBpGXAO6MBAEAX86BBAECEFHEKAyrBSGXAO6MBAEAX86BBAECEFHEKA8jCZFH8jAHCZFGHAS6MBKAEtMDAqCEFGqAL6HoAEHlAqALsMIXBKKARAE9rAM6MDAECBAMZnJJJB8aCEHOINAEG8eAMFHEALAOGXsMDDNARAE9rAM6MBAXCEFHOAECBAMZnJJJB8aA8eMEKKAXAL6HoKCBHEAoCEgMEKAWApAKCUFAL2FALZ+TJJJB8aAKAQFHQAEMEKKCBHOXDKAItMBCBHOINAdAIAO9rAOAdFAI6eAOFGOAI6MBKKCBHOARAE9rCAALALCA6e6MBDNALC8f0MBAECBCAAL9rGOZnJJJBAOFHEKAEAWCJDFALZ+TJJJBALFAB9rHOKAVCJOF8kJJJJBAOK9HEEUAECAAECA0eABCJ/ABAE9uC/wfBgGDCJDADCJD6eGDFCUFAD9uAE2ADCL4CIFCD4ADv2FCEFKMBCBABbDJ+KJJBK/lSE3U8jJJJJBC/AE9rGL8kJJJJBCBHVDNAICI9uGOChFAE0MBABCBYD+E+KJJBGVC/gEv86BBALC/ABFCfECJEZnJJJB8aALCuFGR9CU83IBALC8wFGW9CU83IBALCYFGd9CU83IBALCAFGQ9CU83IBALCkFGK9CU83IBALCZFGX9CU83IBAL9CU83IWAL9CU83IBAEABFC9wFHMABCEFGpAOFHEDNAItMBCMCSAVCB9KGSeHZAVCE9IHhCBHoCBHaCBHcCBHxCBHqINDNAEAM9NMBCBHVXIKAqCUFHVADAcCDTFGOYDBHlAOCWFYDBHkAOCLFYDBHyCBH8aDNDNINALC/ABFAVCSgCITFGOYDLHeDNDNDNAOYDBGOAl9HMBAeAysMEKDNAOAy9HMBAeAk9HMBA8aCEFH8aXEKAOAk9HMEAeAl9HMEA8aCDFH8aKA8aC870MDADA8aCIgCX2GVC+E1JJBFYDBAcFCDTFYDBHyADAVCJ1JJBFYDBAcFCDTFYDBHkALADAVC11JJBFYDBAcFCDTFYDBGeAxZ+FJJJBGVCB9KAVAZ9IgGOCU7AeAosGlgH3DNDNDNDNDNAVCBCSAleAOeGVCS9HMBAhMBAeAeAaAeCEFAasGVeGaCEFsMECMCSAVeHVKApAVA8aCDTC/wEgv86BBAVCS9HMEAeAa9rGVCETAVC8f917HVINAEAVCfB0CRTAVCfBgv86BBAECEFHEAVCJE6HOAVCR4HVAOtMBKAeHaXDKCpHVApA8aCDTCpv86BBAeHaKAVtMBAVAZ9IMEKALAxCDTFAebDBAxCEFCSgHxKAoA3FHoALC/ABFAqCITFGVAybDLAVAebDBALC/ABFAqCEFCSgGVCITFGOAebDLAOAkbDBAVCEFHOXIKAVCUFHVA8aCLFG8aC/AB9HMBKKDNADCEAkAosCETAyAoseCX2GVCJ1JJBFYDBAcFCDTFYDBGetADAVC+E1JJBFYDBAcFCDTFYDBG8aCEsgADAVC11JJBFYDBAcFCDTFYDBGyCDsgAoCB9HgASgG5CE9HMBAR9CU83IBAW9CU83IBAd9CU83IBAQ9CU83IBAK9CU83IBAX9CU83IBAL9CU83IWAL9CU83IBCBHoKAoAeAosGVFHkALA8aAxZ+FJJJBHOALAyAxZ+FJJJBH3DNDNAOCM0MBAOCEFHlXEKCBCSA8aAksGOeHlAkAOFHkKDNDNA3CM0MBA3CEFH3XEKCBCSAyAksGOeH3AkAOFHkKDNDNDNDNDNDNDNDNDNDNDNDNDNDNDNDNDNA3AlCLTvGOCfEgG8eC+qUFp9UISSSSSSSSSSSSSSWSLQMSSSSSSSSSSSSESVSSSSSSSSSSSSSRDSdSSSSSSSSSSSSSSKSSSSSSSSSSSSSSSSOBKC/wEH8fA8epDMKpKC/xEH8fXXKC/yEH8fXKKC/zEH8fXQKC/0EH8fXdKC/1EH8fXWKC/2EH8fXRKC/3EH8fXOKC/4EH8fXVKC/5EH8fXLKC/6EH8fXIKC/7EH8fXDKC/8EH8fXEKCPEH8fKAeAo9HA5vMBApA8f86BBXEKApC9+CUAVe86BBAEAO86BBAECEFHEKDNAVMBAeAa9rGVCETAVC8f917HVINAEAVCfB0GOCRTAVCfBgv86BBAVCR4HVAECEFHEAOMBKAeHaKDNAlCS9HMBA8aAa9rGVCETAVC8f917HVINAEAVCfB0GOCRTAVCfBgv86BBAVCR4HVAECEFHEAOMBKA8aHaKDNA3CS9HMBAyAa9rGVCETAVC8f917HVINAEAVCfB0GOCRTAVCfBgv86BBAVCR4HVAECEFHEAOMBKAyHaKALAxCDTFAebDBAxCEFCSgHVDNDNAlpZBEEEEEEEEEEEEEEBEKALAVCDTFA8abDBAxCDFCSgHVKDNDNA3pZBEEEEEEEEEEEEEEBEKALAVCDTFAybDBAVCEFCSgHVKALC/ABFAqCITFGOAebDLAOA8abDBALC/ABFAqCEFCSgCITFGOA8abDLAOAybDBALC/ABFAqCDFCSgCITFGOAybDLAOAebDBAqCIFHOAVHxAkHoKApCEFHpAOCSgHqAcCIFGcAI6MBKKCBHVAEAM0MBAE9C/lm+i/D+Z+g8a83BWAE9CJ/s+d+0/1+M/e/U+GU83BBAEAB9rCZFHVKALC/AEF8kJJJJBAVK+nIEEUCBHIDNABADCUFCSgCDTFYDBAEsMBCEHIABADCpFCSgCDTFYDBAEsMBCDHIABADCMFCSgCDTFYDBAEsMBCIHIABADCXFCSgCDTFYDBAEsMBCLHIABADCKFCSgCDTFYDBAEsMBCVHIABADCQFCSgCDTFYDBAEsMBCOHIABADCdFCSgCDTFYDBAEsMBCRHIABADCWFCSgCDTFYDBAEsMBCWHIABADCRFCSgCDTFYDBAEsMBCdHIABADCOFCSgCDTFYDBAEsMBCQHIABADCVFCSgCDTFYDBAEsMBCKHIABADCLFCSgCDTFYDBAEsMBCXHIABADCIFCSgCDTFYDBAEsMBCMHIABADCDFCSgCDTFYDBAEsMBCpHIABADCEFCSgCDTFYDBAEsMBCSCUABADCSgCDTFYDBAEseHIKAIKzEEUCBHDDNINADCEFGDC8f0MECEADTAE6MBKKADCRFCfEgCR9uCI2CDFABCI9u2ChFKMBCBABbD+E+KJJBK+cDEWU8jJJJJBCZ9rHLCBHVDNAICVFAE0MBCBHOABCBrB+E+KJJBC/QEv86BBAL9CB83IWABCEFHRAEABFC98FHWDNAItMBCBHdINDNARAW6MBCBSKADAdCDTFYDBGQALCWFAOAQALCWFAOCDTFYDB9rGEAEC8f91GEFAE7C507GOCDTFGKYDB9rGEC8e91C9+gAECDT7AOvHEINARAECfB0GVCRTAECfBgv86BBAECR4HEARCEFHRAVMBKAKAQbDBAdCEFGdAI9HMBKKCBHVARAW0MBARCBbBBARAB9rCLFHVKAVKbEEUCBHDDNINADCEFGDC8f0MECEADTAE6MBKKADCWFCfEgCR9uAB2CVFK+HVOD99EUE99EUI99LUDNDNCUAICUFTCU7+yGVjBBBzmGO+LjBBB9P9dtMBAO+oHRXEKCJJJJ94HRKDNAEtMBCUADCETCUFTCU7+yHWCBHICBHdINALCLFiDBGOjBBBBjBBJzALiDBGQ+LAO+LmALCWFiDBGK+LmGO+VAOjBBBB9beGOnHXAQAOnHOALCXFiDBHQDNDNAKjBBBB9gtMBAXHKXEKjBBJzAO+L+TGKAK+MAXjBBBB9geHKjBBJzAX+L+TGXAX+MAOjBBBB9geHOKDNDNjBBBzjBBB+/AQjBBBB9geAQjBBJ+/AQjBBJ+/9geGQjBBJzAQjBBJz9feAWnmGQ+LjBBB9P9dtMBAQ+oHMXEKCJJJJ94HMKDNDNjBBBzjBBB+/AKjBBBB9geAKjBBJ+/AKjBBJ+/9geGQjBBJzAQjBBJz9feAVnmGQ+LjBBB9P9dtMBAQ+oHpXEKCJJJJ94HpKDNDNjBBBzjBBB+/AOjBBBB9geAOjBBJ+/AOjBBJ+/9geGOjBBJzAOjBBJz9feAVnmGO+LjBBB9P9dtMBAO+oHSXEKCJJJJ94HSKDNDNADCL9HMBABAdFGZAS86BBAZCIFAM86BBAZCDFAR86BBAZCEFAp86BBXEKABAIFGZAS87EBAZCOFAM87EBAZCLFAR87EBAZCDFAp87EBKALCZFHLAICWFHIAdCLFHdAECUFGEMBKKK/KLLD99EUE99EUDNDNCUAICUFTCU7+yGVjBBBzmGO+LjBBB9P9dtMBAO+oHIXEKCJJJJ94HIKDNAEtMBAIC/8fIgHRINABCOFCICDALCLFiDB+LALiDB+L9eGIALCWFiDB+LALAICDTFiDB+L9eeGIALCXFiDB+LALAICDTFiDB+L9eeGIARv87EBDNDNjBBBzjBBB+/ALAICEFCIgCDTFiDBj/zL+1znjBBJ+/jBBJzALAICDTFiDBjBBBB9deGOnGWjBBBB9geAWjBBJ+/AWjBBJ+/9geGWjBBJzAWjBBJz9feAVnmGW+LjBBB9P9dtMBAW+oHdXEKCJJJJ94HdKABAd87EBDNDNjBBBzjBBB+/AOALAICDFCIgCDTFiDBj/zL+1znnGWjBBBB9geAWjBBJ+/AWjBBJ+/9geGWjBBJzAWjBBJz9feAVnmGW+LjBBB9P9dtMBAW+oHdXEKCJJJJ94HdKABCDFAd87EBDNDNjBBBzjBBB+/AOALAICUFCIgCDTFiDBj/zL+1znnGOjBBBB9geAOjBBJ+/AOjBBJ+/9geGOjBBJzAOjBBJz9feAVnmGO+LjBBB9P9dtMBAO+oHIXEKCJJJJ94HIKABCLFAI87EBABCWFHBALCZFHLAECUFGEMBKKK+7DDWUE998jJJJJBCZ9rGV8kJJJJBDNAEtMBADCL6MBCEAI9rHOADCD4GDCEADCE0eHRADCDTHWCBHdINC+cUHDALHIARHQINAIiDBAVCXFZ+XJJJB8aAVYDXGKADADAK9IeHDAICLFHIAQCUFGQMBKAOADFGICkTHKCBHDCBAI9rHXARHIINDNDNALADFiDBGMAXZ+ZJJJBjBBBzjBBB+/AMjBBBB9gemGM+LjBBB9P9dtMBAM+oHQXEKCJJJJ94HQKABADFAQCfffRgAKvbDBADCLFHDAICUFGIMBKABAWFHBALAWFHLAdCEFGdAE9HMBKKAVCZF8kJJJJBK/6ZDkUL998jJJJJBC+QD9rGV8kJJJJBAVC+oEFCBC/kBZnJJJB8aCBHODNADtMBCBHOAItMBDNABAE9HMBAVCUADCDTGOADCffffI0eCBYD/4+JJJBhJJJJBBGEbD+oEAVCEbD1DAEABAOZ+TJJJB8aKCBHRAVC+YEFCWFCBbDBAV9CB83I+YEAVC+YEFAEADAIAVC+oEFZ+OJJJBCUAICDTGWAICffffI0eGdCBYD/4+JJJBhJJJJBBHOAVC+oEFAVYD1DGQCDTFAObDBAVAQCEFGKbD1DAOAVYD+YEGXAWZ+TJJJBHMAVC+oEFAKCDTFADCI9uGpCBYD/4+JJJBhJJJJBBGObDBAVAQCDFGWbD1DAOCBApZnJJJBHSAVC+oEFAWCDTFAdCBYD/4+JJJBhJJJJBBGZbDBAVAQCIFGhbD1DAICEgHoDNAICEsMBAIC9+gHKCBHRALC/EBFHWAZHOAMHIINAOALiDBAWAIYDBGdCWAdCW6eCDTFiDBmuDBAOCLFALiDBAWAICLFYDBGdCWAdCW6eCDTFiDBmuDBAOCWFHOAICWFHIAKARCDFGR9HMBKKDNAotMBAZARCDTGOFALiDBALAMAOFYDBGOCWAOCW6eCDTFC/EBFiDBmuDBKAVC+oEFAhCDTFCUApCDTADCffff970eCBYD/4+JJJBhJJJJBBGRbDBAVAQCLFbD1DDNADCI6MBApCEApCE0eHWAEHOARHIINAIAZAOYDBCDTFiDBAZAOCLFYDBCDTFiDBmAZAOCWFYDBCDTFiDBmuDBAOCXFHOAICLFHIAWCUFGWMBKKAVC/MBFHaAVYD+cEHcAVYD+gEHxAVHWCBHOCBHICBHqCEHlINAWHkAEAICX2FGyCWFG8aYDBHQAyYDBHdABAqCX2FGWCLFAyCLFGeYDBGDbDBAWAdbDBAWCWFAQbDBASAIFCE86BBAaAQbDWAaADbDLAaAdbDBARAICDTFCBbDBDNDNAOMBCIHoXEKAOCEgH3DNDNAOCE9HMBCBHKCIHoXEKAOC8egHhCBHKCIHoAkHOINDNAOYDBGWAdsMBAWADsMBAWAQsMBAaAoCDTFAWbDBAoCEFHoKDNAOCLFYDBGWAdsMBAWADsMBAWAQsMBAaAoCDTFAWbDBAoCEFHoKAOCWFHOAhAKCDFGK9HMBKKA3tMBAkAKCDTFYDBGOAdsMBAOADsMBAOAQsMBAaAoCDTFAObDBAoCEFHoKAMAdCDTFGOAOYDBCUFbDBAMADCDTFGOAOYDBCUFbDBAMAQCDTFGOAOYDBCUFbDBAxAcAyYDBCDTGWFYDBCDTFGDHOAXAWFGKYDBGdHWDNAdtMBDNINAOYDBAIsMEAOCLFHOAWCUFGWtMDXBKKAOAdCDTADFC98FYDBbDBAKAKYDBCUFbDBKAxAcAeYDBCDTGWFYDBCDTFGDHOAXAWFGKYDBGdHWDNAdtMBDNINAOYDBAIsMEAOCLFHOAWCUFGWMBXDKKAOAdCDTADFC98FYDBbDBAKAKYDBCUFbDBKDNAXA8aYDBCDTGOFGKYDBGdtMBAxAcAOFYDBCDTFGDHOAdHWDNINAOYDBAIsMEAOCLFHOAWCUFGWMBXDKKAOAdCDTADFC98FYDBbDBAKAKYDBCUFbDBKDNDNDNAotMBAVYD+YEHyAVYD+cEHeAVYD+gEH8aCUHIjBBBBH5CBHhINAZAaAhGWCDTFYDBCDTGOFGdiDBH8eAdALCBAWCEFGhAWCS0eCDTFiDBALAMAOFYDBGWCWAWCW6eCDTFC/EBFiDBmG8fuDBDNAyAOFYDBGdtMBA8fA8e+THAA8aAeAOFYDBCDTFHWDNDNAdCDTGKC98FGdCLgtMBAWHOXEKARAWYDBGOCDTFGDAAADiDBmG8euDBA8eA5A5A8e9dGDeH5AOAIADeHIAWCLFHOKAdtMBAWAKFHQINARAOYDBGWCDTFGdAAAdiDBmG8euDBARAOCLFYDBGdCDTFGKAAAKiDBmG8fuDBA8fA8eA5A5A8e9dGKeG5A5A8f9dGDeH5AdAWAIAKeADeHIAOCWFGOAQ9HMBKKAhAo9HMBKAICU9HMEKAlAp9PMEINDNASAlFrBBMBAlHIXDKApAlCEFGl9HMBXDKKAqCEFHqAoCZAoCZ6eHOAaHWAkHaAICU9HMEKKAVYD1DHOKAOCDTAVC+oEFFC98FHIDNINAOtMEAIYDBCBYD/0+JJJBh+BJJJBBAIC98FHIAOCUFHOXBKKAVC+QDF8kJJJJBK+HdEdUCBHVCUAICDTGOAICffffI0eGRCBYD/4+JJJBhJJJJBBHWALALYD9gGdCDTFAWbDBALAdCEFbD9gABAWbDBARCBYD/4+JJJBhJJJJBBHWALALYD9gGRCDTFAWbDBALARCEFbD9gABAWbDLCUADCDTADCffffI0eCBYD/4+JJJBhJJJJBBHWALALYD9gGRCDTFAWbDBALARCEFbD9gABAWbDWABYDBCBAOZnJJJB8aADCI9uHQABYDBHODNADtMBADCIgHWDNADCUFCI6MBADC98gHdCBHVAEHLINAOALYDBCDTFGRARYDBCEFbDBAOALCLFYDBCDTFGRARYDBCEFbDBAOALCWFYDBCDTFGRARYDBCEFbDBAOALCXFYDBCDTFGRARYDBCEFbDBALCZFHLAdAVCLFGV9HMBKKDNAWtMBAEAVCDTFHLINAOALYDBCDTFGVAVYDBCEFbDBALCLFHLAWCUFGWMBKKABYDBHOKABYDLHWDNAItMBAICIgHKCBHLCBHXDNAICUFCI6MBAIC98gHMCBHVCBHLCBHXINAWAVFGRALbDBARCLFAOAVFGdYDBALFGLbDBARCWFAdCLFYDBALFGLbDBARCXFAdCWFYDBALFGLbDBAdCXFYDBALFHLAVCZFHVAMAXCLFGX9HMBKKDNAKtMBAWAXCDTGVFHWAOAVFHOINAWALbDBAWCLFHWAOYDBALFHLAOCLFHOAKCUFGKMBKKABYDLHWKDNADCI6MBABYDWHOAQCEAQCE0eHKCBHLINAECWFYDBHVAECLFYDBHRAWAEYDBCDTFGdAdYDBGdCEFbDBAOAdCDTFALbDBAWARCDTFGRARYDBGRCEFbDBAOARCDTFALbDBAWAVCDTFGVAVYDBGVCEFbDBAOAVCDTFALbDBAECXFHEAKALCEFGL9HMBKABYDLHWKDNAItMBABYDBHKAICIgHVCBHRDNAICUFCI6MBAIC98gHXCBHLCBHRINAWALFGEAEYDBAKALFGOYDB9rbDBAECLFGdAdYDBAOCLFYDB9rbDBAECWFGdAdYDBAOCWFYDB9rbDBAECXFGEAEYDBAOCXFYDB9rbDBALCZFHLAXARCLFGR9HMBKKAVtMBAKARCDTGEFHLAWAEFHEINAEAEYDBALYDB9rbDBALCLFHLAECLFHEAVCUFGVMBKKKqBABAEADAIC+k1JJBZ+NJJJBKqBABAEADAIC+M+JJJBZ+NJJJBK/pEELUABCfEAICDTZnJJJBHIDNADMBCBSKADCEgHLDNDNADCE9HMBCBHBCBHVXEKADC9+gHOCBHBAEHDCBHVINDNAIADYDBCDTFGRYDBCU9HMBARABbDBABCEFHBKDNAIADCLFYDBCDTFGRYDBCU9HMBARABbDBABCEFHBKADCWFHDAOAVCDFGV9HMBKKDNALtMBAIAEAVCDTFYDBCDTFGDYDBCU9HMBADABbDBABCEFHBKABK9TEIUCBCBYD/8+JJJBGEABCIFC98gFGBbD/8+JJJBDNDNABzBCZTGD9NMBCUHIABAD9rCffIFCZ4NBCUsMEKAEHIKAIK/3VEIUDNDNAEABvCIgtMBADHIABHLXEKDNDNADCZ9PMBADHIABHLXEKDNDNADC9wFGICZgtMBABHLXEKABAEYDBbDBABAEYDLbDLABAEYDWbDWABAEYDXbDXAECZFHEABCZFHLAIHDKAICZ6MBINALAEYDBbDBALCLFAECLFYDBbDBALCWFAECWFYDBbDBALCXFAECXFYDBbDBALCZFAECZFYDBbDBALCcFAECcFYDBbDBALCkFAECkFYDBbDBALC3FAEC3FYDBbDBALCAFHLAECAFHEADC9gFGDCS0MBKADHIKAICL6MBDNAIC98FGVCD4CEFCRgGDtMBINALAEYDBbDBAIC98FHIAECLFHEALCLFHLADCUFGDMBKKAVC36MBINALAEYDBbDBALCLFAECLFYDBbDBALCWFAECWFYDBbDBALCXFAECXFYDBbDBALCZFAECZFYDBbDBALCcFAECcFYDBbDBALCkFAECkFYDBbDBALC3FAEC3FYDBbDBALCAFHLAECAFHEAIC9gFGICI0MBKKDNAItMBAICUFHVDNAICRgGDtMBINALAErBB86BBAICUFHIALCEFHLAECEFHEADCUFGDMBKKAVCR6MBINALAErBB86BBALCEFAECEFrBB86BBALCDFAECDFrBB86BBALCIFAECIFrBB86BBALCLFAECLFrBB86BBALCVFAECVFrBB86BBALCOFAECOFrBB86BBALCRFAECRFrBB86BBALCWFHLAECWFHEAIC94FGIMBKKABK+nVELUDNDNABCIgtMBABHIXEKAECfEgC+B+C+EW2HLDNDNADCZ9PMBABHIXEKDNDNADC9wFGVCL4CEFCIgGOMBABHIXEKABHIINAIALbDBAICXFALbDBAICWFALbDBAICLFALbDBAICZFHIADC9wFHDAOCUFGOMBKKAVC8w6MBINAIALbDBAIC88FALbDBAICuFALbDBAIC80FALbDBAIC8wFALbDBAIC8sFALbDBAICYFALbDBAIC8kFALbDBAICAFALbDBAIC3FALbDBAICkFALbDBAICcFALbDBAICZFALbDBAICXFALbDBAICWFALbDBAICLFALbDBAIC/ABFHIADCNFGDCS0MBKKADCL6MBDNADC98FGVCD4CEFCRgGOtMBINAIALbDBADC98FHDAICLFHIAOCUFGOMBKKAVC36MBINAIALbDBAIC3FALbDBAICkFALbDBAICcFALbDBAICZFALbDBAICXFALbDBAICWFALbDBAICLFALbDBAICAFHIADC9gFGDCI0MBKKDNADtMBADCUFHODNADCRgGLtMBINAIAE86BBADCUFHDAICEFHIALCUFGLMBKKAOCR6MBINAIAE86BBAICRFAE86BBAICOFAE86BBAICVFAE86BBAICLFAE86BBAICIFAE86BBAICDFAE86BBAICEFAE86BBAICWFHIADC94FGDMBKKABK9TEIUCBCBYD/8+JJJBGEABCIFC98gFGBbD/8+JJJBDNDNABzBCZTGD9NMBCUHIABAD9rCffIFCZ4NBCUsMEKAEHIKAIK9+EIUzBHEDNDNCBYD/8+JJJBGDAECZTGI9NMBCUHEADAI9rCffIFCZ4NBCUsMEKADHEKCBABAE9rCIFC98gCBYD/8+JJJBFGDbD/8+JJJBDNADzBCZTGE9NMBADAE9rCffIFCZ4NB8aKK+BEEIUDNAB+8GDCl4GICfEgGLCfEsMBDNALMBDNABjBBBB9cMBAECBbDBABSKABjBBJ9fnAEZ+XJJJBHBAEAEYDBCNFbDBABSKAEAICfEgC+CUFbDBADCfff+D94gCJJJ/4Iv++HBKABK+gEBDNDNAECJE9IMBABjBBBUnHBDNAECfE9OMBAEC+BUFHEXDKABjBBBUnHBAECPDAECPD9IeC+C9+FHEXEKAEC+BU9KMBABjBBJXnHBDNAEC+b9+9MMBAEC/mBFHEXEKABjBBJXnHBAEC+299AEC+2999KeC/MEFHEKABAEClTCJJJ/8IF++nKXBABAEZ+YJJJBKK+ODDBCJWK/0EBBBBEBBBDBBBEBBBDBBBBBBBDBBBBBBBEBBBBBBB+L29Hz/69+9Kz/n/76z/RG97z/Z/O9Xz8j/b85z/+/U9Yz/B/K9hz+2/z9dz9E+L9Mz59a8kz+R/t3z+a+Zyz79ohz/J4++8++y+d9v8+BBBB9S+49+z8r+Hbz9m9m/m8+l/Z/O8+/8+pg89Q/X+j878r+Hq8++m+b/E87BBBBBBJzBBJzBBJz+e/v/n8++y+dSz9I/h/68+XD/r8+/H0838+/w+nOzBBBB+wv9o8+UF888+9I/h/68+9C9g/l89/N/M9M89/d8kO8+BBBBF+8Tz9M836zs+2azl/Zpzz818ez9E+LXz/u98f8+819e/68+BC/0dKXEBBBDBBBZwBB";

	// Used to unpack wasm
	var wasmpack = new Uint8Array([32,0,65,2,1,106,34,33,3,128,11,4,13,64,6,253,10,7,15,116,127,5,8,12,40,16,19,54,20,9,27,255,113,17,42,67,24,23,146,148,18,14,22,45,70,69,56,114,101,21,25,63,75,136,108,28,118,29,73,115]);

	if (typeof WebAssembly !== 'object') {
		// This module requires WebAssembly to function
		return {
			supported: false,
		};
	}

	var instance;

	var promise =
		WebAssembly.instantiate(unpack(wasm), {})
		.then(function(result) {
			instance = result.instance;
			instance.exports.__wasm_call_ctors();
			instance.exports.meshopt_encodeVertexVersion(0);
			instance.exports.meshopt_encodeIndexVersion(1);
		});

	function unpack(data) {
		var result = new Uint8Array(data.length);
		for (var i = 0; i < data.length; ++i) {
			var ch = data.charCodeAt(i);
			result[i] = ch > 96 ? ch - 71 : ch > 64 ? ch - 65 : ch > 47 ? ch + 4 : ch > 46 ? 63 : 62;
		}
		var write = 0;
		for (var i = 0; i < data.length; ++i) {
			result[write++] = (result[i] < 60) ? wasmpack[result[i]] : (result[i] - 60) * 64 + result[++i];
		}
		return result.buffer.slice(0, write);
	}

	function assert(cond) {
		if (!cond) {
			throw new Error("Assertion failed");
		}
	}

	function reorder(indices, vertices, optf) {
		var sbrk = instance.exports.sbrk;
		var ip = sbrk(indices.length * 4);
		var rp = sbrk(vertices * 4);
		var heap = new Uint8Array(instance.exports.memory.buffer);
		var indices8 = new Uint8Array(indices.buffer, indices.byteOffset, indices.byteLength);
		heap.set(indices8, ip);
		if (optf) {
			optf(ip, ip, indices.length, vertices);
		}
		var unique = instance.exports.meshopt_optimizeVertexFetchRemap(rp, ip, indices.length, vertices);
		// heap may have grown
		heap = new Uint8Array(instance.exports.memory.buffer);
		var remap = new Uint32Array(vertices);
		new Uint8Array(remap.buffer).set(heap.subarray(rp, rp + vertices * 4));
		indices8.set(heap.subarray(ip, ip + indices.length * 4));
		sbrk(ip - sbrk(0));

		for (var i = 0; i < indices.length; ++i)
			indices[i] = remap[indices[i]];

		return [remap, unique];
	}

	function encode(fun, bound, source, count, size) {
		var sbrk = instance.exports.sbrk;
		var tp = sbrk(bound);
		var sp = sbrk(count * size);
		var heap = new Uint8Array(instance.exports.memory.buffer);
		heap.set(new Uint8Array(source.buffer, source.byteOffset, source.byteLength), sp);
		var res = fun(tp, bound, sp, count, size);
		var target = new Uint8Array(res);
		target.set(heap.subarray(tp, tp + res));
		sbrk(tp - sbrk(0));
		return target;
	}

	function maxindex(source) {
		var result = 0;
		for (var i = 0; i < source.length; ++i) {
			var index = source[i];
			result = result < index ? index : result;
		}
		return result;
	}

	function index32(source, size) {
		assert(size == 2 || size == 4);
		if (size == 4) {
			return new Uint32Array(source.buffer, source.byteOffset, source.byteLength / 4);
		} else {
			var view = new Uint16Array(source.buffer, source.byteOffset, source.byteLength / 2);
			return new Uint32Array(view); // copies each element
		}
	}

	function filter(fun, source, count, stride, bits, insize) {
		var sbrk = instance.exports.sbrk;
		var tp = sbrk(count * stride);
		var sp = sbrk(count * insize);
		var heap = new Uint8Array(instance.exports.memory.buffer);
		heap.set(new Uint8Array(source.buffer, source.byteOffset, source.byteLength), sp);
		fun(tp, count, stride, bits, sp);
		var target = new Uint8Array(count * stride);
		target.set(heap.subarray(tp, tp + count * stride));
		sbrk(tp - sbrk(0));
		return target;
	}

	return {
		ready: promise,
		supported: true,
		reorderMesh: function(indices, triangles, optsize) {
			var optf = triangles ? (optsize ? instance.exports.meshopt_optimizeVertexCacheStrip : instance.exports.meshopt_optimizeVertexCache) : undefined;
			return reorder(indices, maxindex(indices) + 1, optf);
		},
		encodeVertexBuffer: function(source, count, size) {
			assert(size > 0 && size <= 256);
			assert(size % 4 == 0);
			var bound = instance.exports.meshopt_encodeVertexBufferBound(count, size);
			return encode(instance.exports.meshopt_encodeVertexBuffer, bound, source, count, size);
		},
		encodeIndexBuffer: function(source, count, size) {
			assert(size == 2 || size == 4);
			assert(count % 3 == 0);
			var indices = index32(source, size);
			var bound = instance.exports.meshopt_encodeIndexBufferBound(count, maxindex(indices) + 1);
			return encode(instance.exports.meshopt_encodeIndexBuffer, bound, indices, count, 4);
		},
		encodeIndexSequence: function(source, count, size) {
			assert(size == 2 || size == 4);
			var indices = index32(source, size);
			var bound = instance.exports.meshopt_encodeIndexSequenceBound(count, maxindex(indices) + 1);
			return encode(instance.exports.meshopt_encodeIndexSequence, bound, indices, count, 4);
		},
		encodeGltfBuffer: function(source, count, size, mode) {
			var table = {
				ATTRIBUTES: this.encodeVertexBuffer,
				TRIANGLES: this.encodeIndexBuffer,
				INDICES: this.encodeIndexSequence,
			};
			assert(table[mode]);
			return table[mode](source, count, size);
		},
		encodeFilterOct: function(source, count, stride, bits) {
			assert(stride == 4 || stride == 8);
			assert(bits >= 1 && bits <= 16);
			return filter(instance.exports.meshopt_encodeFilterOct, source, count, stride, bits, 16);
		},
		encodeFilterQuat: function(source, count, stride, bits) {
			assert(stride == 8);
			assert(bits >= 4 && bits <= 16);
			return filter(instance.exports.meshopt_encodeFilterQuat, source, count, stride, bits, 16);
		},
		encodeFilterExp: function(source, count, stride, bits) {
			assert(stride > 0 && stride % 4 == 0);
			assert(bits >= 1 && bits <= 24);
			return filter(instance.exports.meshopt_encodeFilterExp, source, count, stride, bits, stride);
		},
	};
})();

export { MeshoptEncoder };
