# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/betto/src/meshoptimizer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/betto/src/meshoptimizer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"meshoptimizer\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/betto/src/meshoptimizer/CMakeFiles /home/betto/src/meshoptimizer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/betto/src/meshoptimizer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named meshoptimizer

# Build rule for target.
meshoptimizer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 meshoptimizer
.PHONY : meshoptimizer

# fast build rule for target.
meshoptimizer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/build
.PHONY : meshoptimizer/fast

src/allocator.o: src/allocator.cpp.o
.PHONY : src/allocator.o

# target to build an object file
src/allocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/allocator.cpp.o
.PHONY : src/allocator.cpp.o

src/allocator.i: src/allocator.cpp.i
.PHONY : src/allocator.i

# target to preprocess a source file
src/allocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/allocator.cpp.i
.PHONY : src/allocator.cpp.i

src/allocator.s: src/allocator.cpp.s
.PHONY : src/allocator.s

# target to generate assembly for a file
src/allocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/allocator.cpp.s
.PHONY : src/allocator.cpp.s

src/clusterizer.o: src/clusterizer.cpp.o
.PHONY : src/clusterizer.o

# target to build an object file
src/clusterizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/clusterizer.cpp.o
.PHONY : src/clusterizer.cpp.o

src/clusterizer.i: src/clusterizer.cpp.i
.PHONY : src/clusterizer.i

# target to preprocess a source file
src/clusterizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/clusterizer.cpp.i
.PHONY : src/clusterizer.cpp.i

src/clusterizer.s: src/clusterizer.cpp.s
.PHONY : src/clusterizer.s

# target to generate assembly for a file
src/clusterizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/clusterizer.cpp.s
.PHONY : src/clusterizer.cpp.s

src/indexcodec.o: src/indexcodec.cpp.o
.PHONY : src/indexcodec.o

# target to build an object file
src/indexcodec.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/indexcodec.cpp.o
.PHONY : src/indexcodec.cpp.o

src/indexcodec.i: src/indexcodec.cpp.i
.PHONY : src/indexcodec.i

# target to preprocess a source file
src/indexcodec.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/indexcodec.cpp.i
.PHONY : src/indexcodec.cpp.i

src/indexcodec.s: src/indexcodec.cpp.s
.PHONY : src/indexcodec.s

# target to generate assembly for a file
src/indexcodec.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/indexcodec.cpp.s
.PHONY : src/indexcodec.cpp.s

src/indexgenerator.o: src/indexgenerator.cpp.o
.PHONY : src/indexgenerator.o

# target to build an object file
src/indexgenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/indexgenerator.cpp.o
.PHONY : src/indexgenerator.cpp.o

src/indexgenerator.i: src/indexgenerator.cpp.i
.PHONY : src/indexgenerator.i

# target to preprocess a source file
src/indexgenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/indexgenerator.cpp.i
.PHONY : src/indexgenerator.cpp.i

src/indexgenerator.s: src/indexgenerator.cpp.s
.PHONY : src/indexgenerator.s

# target to generate assembly for a file
src/indexgenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/indexgenerator.cpp.s
.PHONY : src/indexgenerator.cpp.s

src/overdrawanalyzer.o: src/overdrawanalyzer.cpp.o
.PHONY : src/overdrawanalyzer.o

# target to build an object file
src/overdrawanalyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/overdrawanalyzer.cpp.o
.PHONY : src/overdrawanalyzer.cpp.o

src/overdrawanalyzer.i: src/overdrawanalyzer.cpp.i
.PHONY : src/overdrawanalyzer.i

# target to preprocess a source file
src/overdrawanalyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/overdrawanalyzer.cpp.i
.PHONY : src/overdrawanalyzer.cpp.i

src/overdrawanalyzer.s: src/overdrawanalyzer.cpp.s
.PHONY : src/overdrawanalyzer.s

# target to generate assembly for a file
src/overdrawanalyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/overdrawanalyzer.cpp.s
.PHONY : src/overdrawanalyzer.cpp.s

src/overdrawoptimizer.o: src/overdrawoptimizer.cpp.o
.PHONY : src/overdrawoptimizer.o

# target to build an object file
src/overdrawoptimizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/overdrawoptimizer.cpp.o
.PHONY : src/overdrawoptimizer.cpp.o

src/overdrawoptimizer.i: src/overdrawoptimizer.cpp.i
.PHONY : src/overdrawoptimizer.i

# target to preprocess a source file
src/overdrawoptimizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/overdrawoptimizer.cpp.i
.PHONY : src/overdrawoptimizer.cpp.i

src/overdrawoptimizer.s: src/overdrawoptimizer.cpp.s
.PHONY : src/overdrawoptimizer.s

# target to generate assembly for a file
src/overdrawoptimizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/overdrawoptimizer.cpp.s
.PHONY : src/overdrawoptimizer.cpp.s

src/simplifier.o: src/simplifier.cpp.o
.PHONY : src/simplifier.o

# target to build an object file
src/simplifier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/simplifier.cpp.o
.PHONY : src/simplifier.cpp.o

src/simplifier.i: src/simplifier.cpp.i
.PHONY : src/simplifier.i

# target to preprocess a source file
src/simplifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/simplifier.cpp.i
.PHONY : src/simplifier.cpp.i

src/simplifier.s: src/simplifier.cpp.s
.PHONY : src/simplifier.s

# target to generate assembly for a file
src/simplifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/simplifier.cpp.s
.PHONY : src/simplifier.cpp.s

src/spatialorder.o: src/spatialorder.cpp.o
.PHONY : src/spatialorder.o

# target to build an object file
src/spatialorder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/spatialorder.cpp.o
.PHONY : src/spatialorder.cpp.o

src/spatialorder.i: src/spatialorder.cpp.i
.PHONY : src/spatialorder.i

# target to preprocess a source file
src/spatialorder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/spatialorder.cpp.i
.PHONY : src/spatialorder.cpp.i

src/spatialorder.s: src/spatialorder.cpp.s
.PHONY : src/spatialorder.s

# target to generate assembly for a file
src/spatialorder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/spatialorder.cpp.s
.PHONY : src/spatialorder.cpp.s

src/stripifier.o: src/stripifier.cpp.o
.PHONY : src/stripifier.o

# target to build an object file
src/stripifier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/stripifier.cpp.o
.PHONY : src/stripifier.cpp.o

src/stripifier.i: src/stripifier.cpp.i
.PHONY : src/stripifier.i

# target to preprocess a source file
src/stripifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/stripifier.cpp.i
.PHONY : src/stripifier.cpp.i

src/stripifier.s: src/stripifier.cpp.s
.PHONY : src/stripifier.s

# target to generate assembly for a file
src/stripifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/stripifier.cpp.s
.PHONY : src/stripifier.cpp.s

src/vcacheanalyzer.o: src/vcacheanalyzer.cpp.o
.PHONY : src/vcacheanalyzer.o

# target to build an object file
src/vcacheanalyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vcacheanalyzer.cpp.o
.PHONY : src/vcacheanalyzer.cpp.o

src/vcacheanalyzer.i: src/vcacheanalyzer.cpp.i
.PHONY : src/vcacheanalyzer.i

# target to preprocess a source file
src/vcacheanalyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vcacheanalyzer.cpp.i
.PHONY : src/vcacheanalyzer.cpp.i

src/vcacheanalyzer.s: src/vcacheanalyzer.cpp.s
.PHONY : src/vcacheanalyzer.s

# target to generate assembly for a file
src/vcacheanalyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vcacheanalyzer.cpp.s
.PHONY : src/vcacheanalyzer.cpp.s

src/vcacheoptimizer.o: src/vcacheoptimizer.cpp.o
.PHONY : src/vcacheoptimizer.o

# target to build an object file
src/vcacheoptimizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vcacheoptimizer.cpp.o
.PHONY : src/vcacheoptimizer.cpp.o

src/vcacheoptimizer.i: src/vcacheoptimizer.cpp.i
.PHONY : src/vcacheoptimizer.i

# target to preprocess a source file
src/vcacheoptimizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vcacheoptimizer.cpp.i
.PHONY : src/vcacheoptimizer.cpp.i

src/vcacheoptimizer.s: src/vcacheoptimizer.cpp.s
.PHONY : src/vcacheoptimizer.s

# target to generate assembly for a file
src/vcacheoptimizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vcacheoptimizer.cpp.s
.PHONY : src/vcacheoptimizer.cpp.s

src/vertexcodec.o: src/vertexcodec.cpp.o
.PHONY : src/vertexcodec.o

# target to build an object file
src/vertexcodec.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vertexcodec.cpp.o
.PHONY : src/vertexcodec.cpp.o

src/vertexcodec.i: src/vertexcodec.cpp.i
.PHONY : src/vertexcodec.i

# target to preprocess a source file
src/vertexcodec.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vertexcodec.cpp.i
.PHONY : src/vertexcodec.cpp.i

src/vertexcodec.s: src/vertexcodec.cpp.s
.PHONY : src/vertexcodec.s

# target to generate assembly for a file
src/vertexcodec.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vertexcodec.cpp.s
.PHONY : src/vertexcodec.cpp.s

src/vertexfilter.o: src/vertexfilter.cpp.o
.PHONY : src/vertexfilter.o

# target to build an object file
src/vertexfilter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vertexfilter.cpp.o
.PHONY : src/vertexfilter.cpp.o

src/vertexfilter.i: src/vertexfilter.cpp.i
.PHONY : src/vertexfilter.i

# target to preprocess a source file
src/vertexfilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vertexfilter.cpp.i
.PHONY : src/vertexfilter.cpp.i

src/vertexfilter.s: src/vertexfilter.cpp.s
.PHONY : src/vertexfilter.s

# target to generate assembly for a file
src/vertexfilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vertexfilter.cpp.s
.PHONY : src/vertexfilter.cpp.s

src/vfetchanalyzer.o: src/vfetchanalyzer.cpp.o
.PHONY : src/vfetchanalyzer.o

# target to build an object file
src/vfetchanalyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vfetchanalyzer.cpp.o
.PHONY : src/vfetchanalyzer.cpp.o

src/vfetchanalyzer.i: src/vfetchanalyzer.cpp.i
.PHONY : src/vfetchanalyzer.i

# target to preprocess a source file
src/vfetchanalyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vfetchanalyzer.cpp.i
.PHONY : src/vfetchanalyzer.cpp.i

src/vfetchanalyzer.s: src/vfetchanalyzer.cpp.s
.PHONY : src/vfetchanalyzer.s

# target to generate assembly for a file
src/vfetchanalyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vfetchanalyzer.cpp.s
.PHONY : src/vfetchanalyzer.cpp.s

src/vfetchoptimizer.o: src/vfetchoptimizer.cpp.o
.PHONY : src/vfetchoptimizer.o

# target to build an object file
src/vfetchoptimizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vfetchoptimizer.cpp.o
.PHONY : src/vfetchoptimizer.cpp.o

src/vfetchoptimizer.i: src/vfetchoptimizer.cpp.i
.PHONY : src/vfetchoptimizer.i

# target to preprocess a source file
src/vfetchoptimizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vfetchoptimizer.cpp.i
.PHONY : src/vfetchoptimizer.cpp.i

src/vfetchoptimizer.s: src/vfetchoptimizer.cpp.s
.PHONY : src/vfetchoptimizer.s

# target to generate assembly for a file
src/vfetchoptimizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshoptimizer.dir/build.make CMakeFiles/meshoptimizer.dir/src/vfetchoptimizer.cpp.s
.PHONY : src/vfetchoptimizer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... meshoptimizer"
	@echo "... src/allocator.o"
	@echo "... src/allocator.i"
	@echo "... src/allocator.s"
	@echo "... src/clusterizer.o"
	@echo "... src/clusterizer.i"
	@echo "... src/clusterizer.s"
	@echo "... src/indexcodec.o"
	@echo "... src/indexcodec.i"
	@echo "... src/indexcodec.s"
	@echo "... src/indexgenerator.o"
	@echo "... src/indexgenerator.i"
	@echo "... src/indexgenerator.s"
	@echo "... src/overdrawanalyzer.o"
	@echo "... src/overdrawanalyzer.i"
	@echo "... src/overdrawanalyzer.s"
	@echo "... src/overdrawoptimizer.o"
	@echo "... src/overdrawoptimizer.i"
	@echo "... src/overdrawoptimizer.s"
	@echo "... src/simplifier.o"
	@echo "... src/simplifier.i"
	@echo "... src/simplifier.s"
	@echo "... src/spatialorder.o"
	@echo "... src/spatialorder.i"
	@echo "... src/spatialorder.s"
	@echo "... src/stripifier.o"
	@echo "... src/stripifier.i"
	@echo "... src/stripifier.s"
	@echo "... src/vcacheanalyzer.o"
	@echo "... src/vcacheanalyzer.i"
	@echo "... src/vcacheanalyzer.s"
	@echo "... src/vcacheoptimizer.o"
	@echo "... src/vcacheoptimizer.i"
	@echo "... src/vcacheoptimizer.s"
	@echo "... src/vertexcodec.o"
	@echo "... src/vertexcodec.i"
	@echo "... src/vertexcodec.s"
	@echo "... src/vertexfilter.o"
	@echo "... src/vertexfilter.i"
	@echo "... src/vertexfilter.s"
	@echo "... src/vfetchanalyzer.o"
	@echo "... src/vfetchanalyzer.i"
	@echo "... src/vfetchanalyzer.s"
	@echo "... src/vfetchoptimizer.o"
	@echo "... src/vfetchoptimizer.i"
	@echo "... src/vfetchoptimizer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

